name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies ⌛
        run: npm ci

      - name: Run e2e and API tests 🎭
        run: |
          npx playwright test --project=e2e-chromium
          npx playwright test --project=api
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          PASSWORD_USER: ${{ secrets.PASSWORD_USER }}
          EMAIL_MANAGER: ${{ secrets.EMAIL_MANAGER }}
          PASSWORD_MANAGER: ${{ secrets.PASSWORD_MANAGER }}
          HTTP_CREDENTIALS_USERNAME: ${{ secrets.HTTP_CREDENTIALS_USERNAME }}
          HTTP_CREDENTIALS_PASSWORD: ${{ secrets.HTTP_CREDENTIALS_PASSWORD }}
          API_URL: ${{ secrets.API_URL }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
          TESTOMATIO: ${{ secrets.TESTOMATIO }}

      - name: Upload test results 📝
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: playwright-report/
          retention-days: 5
